WBG="wasm-bindgen 0.2.95"
if [ "$(wasm-bindgen -V)" != "$WBG" ]; then
	echo "Incorrect wasm-bindgen version: '$(wasm-bindgen -V)' != '$WBG'"
	exit 1
fi

mkdir pkg
RUSTFLAGS='-C target-feature=+atomics,+bulk-memory' cargo build --target wasm32-unknown-unknown -Z build-std=panic_abort,std --release "$@"
wasm-bindgen --target web --out-dir pkg/ target/wasm32-unknown-unknown/release/wisp_iwa_rust.wasm
AUTOGENERATED_SOURCE=$(<"pkg/wisp_iwa_rust.js")
AUTOGENERATED_SOURCE=${AUTOGENERATED_SOURCE//getObject(arg0).send(getArrayU8FromWasm0(arg1, arg2)/getObject(arg0).send(new Uint8Array(getArrayU8FromWasm0(arg1, arg2)).buffer}
WASM_BASE64=$(base64 -w0 pkg/wisp_iwa_rust_bg.wasm)
AUTOGENERATED_SOURCE=${AUTOGENERATED_SOURCE//__wbg_init(module_or_path) \{/__wbg_init(module_or_path) \{$'\n\t'module_or_path = module_or_path || $'{};\n\t'module_or_path.module_or_path=new URL(\'data:application/wasm;base64,$WASM_BASE64\')}
echo "$AUTOGENERATED_SOURCE" > "pkg/wisp_iwa_rust.js"
